### ISSUE TITLE
Is this only a concern for equality checks not range?

### ISSUE THREAD

**Issue by polarathene** [mikedilger/float-cmp#9]
From the given methods and links it seems to be about accuracy with comparing equality. If I'm querying a range with something like `0.0 <= x && x <= 1.0` along with any other similar range queries(where it could be in increments of `1.0`), is likely I can run into equality errors(perhaps when comparing equality to 0.0 or 1.0)?

If that's an issue do I need to perform the comparison  in addition to equality checks at the start/end ranges with float-cmp?

**Comment by mikedilger** [comment]
In general, to get consistent results you should use the Ulps function variants (not the Ratio one), and use comparison checks like this, rather than the built-in "<=" operator:
````rust
  use float_cmp::ApproxOrdUlps;

   x.approx_ge(0.0, ulps) && x.approx_le(1.0, ulps)
````

Behavior is a bit tricky around 0.0.  If x is very very slightly less than 0.0, approx_ge() will return false, even if it is within the ulps range, because the sign is wrong and most people consider the sign to be more important of a change.  That is, it will ignore the approximation on negative side of zero.  As for 1.0, if it is very very slightly greater, it will call it close enough due to the ulps parameter.  Usually this is actually what you want.  IIRC floating point instability won't switch the sign.
